#!/usr/bin/env python

from lib.factory.builder_factory import BuilderFactory
import sys

if len(sys.argv) != 3:
    print "Usage: %s nodes flavor" % sys.argv[0]
    sys.exit(1)
    
builder = BuilderFactory.create_builder(sys.argv[2])
builder.build_cluster(int(sys.argv[1]))


