- hosts: mpi_nodes
  sudo: True
  tasks: 

    - name: Update apt repositories
      action: apt update_cache=True

    - name : Install dependencies
      action: apt pkg={{ item }} state=latest
      with_items:
        - gcc
        - make
        - mpich2
        - libnss-myhostname
        - openmpi-bin
        
    - name : Add mpi user
      user: name=mpiuser state=present generate_ssh_key=yes password=mpiuser

    - name: Create directory for ssh keys
      action: file path=/home/mpiuser/.ssh state=directory mode=750 owner=mpiuser group=mpiuser 

    - name: Copy authorized_keys to allow mpi acces through ssh
      action: command cp /home/ubuntu/.ssh/authorized_keys /home/mpiuser/.ssh

    - name: Change the right on authorized_keys
      action: command chown mpiuser:mpiuser /home/mpiuser/.ssh/authorized_keys
