#!/usr/bin/env python

from lib.factory.service_factory import ServiceFactory
import time

service_factory = ServiceFactory()
net_service = service_factory.create_network_service()
sec_service = service_factory.create_security_service()
server_service = service_factory.create_server_service()

network_id = net_service.setup_network()
sec_service.setup_security()
time.sleep(3)
servers = server_service.boot_servers(10, network_id)

for server in servers:
    net_service.assign_ip(server)
checker = service_factory.create_node_checker()
checker.wait_for_nodes(servers)
